rm -rf db
rm -rf greybox_tmp
rm -rf output_files
rm -rf soc_system/simulation
rm -rf soc_system/synthesis
rm -rf soc_system/*.rpt
rm -rf soc_system/*.xml
rm -rf soc_system/*.html
rm -rf soc_system/*.bsf
rm -rf incremental_db
rm -rf *.rpt
rm -rf *.tcl~
rm -rf *.csv
rm -rf *.qws
rm -rf *.rbf
rm -rf *.sopcinfo
rm -rf c5_pin*.txt
rm -rf hps_isw_handoff/soc_system_hps_0
rm -rf .qsys_edit
rm -rf software/spl_bsp/generated
rm -f  software/spl_bsp/*.ds
rm -f  software/spl_bsp/*.bsp
rm -f  software/spl_bsp/*.bin
rm -rf software/spl_bsp/uboot-socfpga
rm -rf soc_system
rm -rf hps_isw_handoff
rm -f  hps_0.h
